dist: trusty
language: java
sudo: false
jdk:
  - oraclejdk8

script: "mvn clean test -Dtest=!*IT -Dmaven.javadoc.skip=true -B -V"

after_success:
  - mvn clean integration-test -Dtest=!*Test jacoco:report coveralls:report #generate Jacoco reports